import AsyncStorage from "@react-native-async-storage/async-storage";
import { createContext, useContext, useEffect, useState } from "react";
// ===== Sync with SoundManager =====

export const GameContext = createContext({});

export function GameProvider({ children }) {
  const [players, setPlayers] = useState([]);
  const [impostorIds, setImpostorIds] = useState([]);
  const [word, setWord] = useState("");
  const [hint, setHint] = useState(""); // 💡 NUEVO: hint
  const [gameWinner, setGameWinner] = useState(null);
  const [alivePlayers, setAlivePlayers] = useState([]);
  const [category, setCategory] = useState(null);
  const [subCategory, setSubCategory] = useState(null);
  const [hintsEnabled, setHintsEnabled] = useState(true); // o false por defecto

  // ⚙️ Configuración guardada
  const [soundEnabled, setSoundEnabled] = useState(true);
  const [impostorCount, setImpostorCount] = useState(1);

  useEffect(() => {
  const loadSettings = async () => {
    try {
      const savedSound = await AsyncStorage.getItem("soundEnabled");
      const savedImpostorCount = await AsyncStorage.getItem("impostorCount");
      const savedHintsEnabled = await AsyncStorage.getItem("hintsEnabled");

      if (savedSound !== null) setSoundEnabled(JSON.parse(savedSound));
      if (savedImpostorCount !== null) setImpostorCount(Number(savedImpostorCount));
      if (savedHintsEnabled !== null) setHintsEnabled(JSON.parse(savedHintsEnabled));
    } catch (e) {
      console.warn("⚠️ Error cargando configuraciones:", e);
    }
  };
  loadSettings();
}, []);

useEffect(() => {
  AsyncStorage.setItem("soundEnabled", JSON.stringify(soundEnabled));
}, [soundEnabled]);

useEffect(() => {
  AsyncStorage.setItem("impostorCount", impostorCount.toString());
}, [impostorCount]);

useEffect(() => {
  AsyncStorage.setItem("hintsEnabled", JSON.stringify(hintsEnabled));
}, [hintsEnabled]);

  // 📚 Palabras + pistas
  const defaultWords = {
    general: {
    general: [
        { word: "Pelota", hint: "Indispensable" },
        { word: "Arco", hint: "Objetivo" },
        { word: "Césped", hint: "Verde" },
        { word: "Árbitro", hint: "Justicia" },
        { word: "Offside", hint: "Posición" },
        { word: "Corner", hint: "Esquina" },
        { word: "Penal", hint: "Pena" },
        { word: "Tiro libre", hint: "Falta" },
        { word: "Saque de banda", hint: "Manos" },
        { word: "Campeón", hint: "Trofeo" },
        { word: "Defensa", hint: "Bloqueo" },
        { word: "Delantero", hint: "Gol" },
        { word: "Mediocampista", hint: "Enlace" },
        { word: "Portero", hint: "Manos" },
        { word: "Entrenador", hint: "Decisiones" },
        { word: "Hincha", hint: "12" },
        { word: "Derbi", hint: "Rivalidad" },
        { word: "Camiseta", hint: "Identidad" },
        { word: "Balón de Oro", hint: "Premio" },
        { word: "Táctica", hint: "Plan" },
        { word: "Formación", hint: "Estructura" },
        { word: "Presión", hint: "Intensidad" },
        { word: "Contraataque", hint: "Rapidez" },
        { word: "Gambeta", hint: "Habilidad" },
        { word: "Cabeceo", hint: "Altura" },
        { word: "Asistencia", hint: "Previo" },
        { word: "Línea defensiva", hint: "Orden" },
        { word: "Extremo", hint: "Banda" },
        { word: "Enganche", hint: "Creatividad" },
        { word: "Capitán", hint: "Referencia" },
        { word: "Partido", hint: "Encuentro" },
        { word: "Gol", hint: "Explosión" },
        { word: "Equipo", hint: "Conjunto" },
        { word: "Cancha", hint: "Escenario" },
        { word: "Tiempo", hint: "Reloj" },
        { word: "Resultado", hint: "Balance" },
        { word: "Victoria", hint: "Alegría" },
        { word: "Derrota", hint: "Silencio" },
        { word: "Empate", hint: "Igualdad" },
        { word: "Competencia", hint: "Nivel" },
        { word: "Estadio", hint: "Multitud" },
        { word: "Tribuna", hint: "Aliento" },
        { word: "Aplausos", hint: "Reconocimiento" },
        { word: "Silbidos", hint: "Desaprobación" },
        { word: "Clima", hint: "Condición" },
        { word: "Jugador", hint: "Protagonista" },
        { word: "Rival", hint: "Oposición" },
        { word: "Público", hint: "Presencia" },
        { word: "Equipo técnico", hint: "Apoyo" },
        { word: "Plantel", hint: "Grupo" },
        { word: "Torneo", hint: "Competición" },
        { word: "Liga", hint: "Campeonato" },
        { word: "Copa", hint: "Eliminación" },
        { word: "Selección", hint: "Nacional" },
        { word: "Mundial", hint: "Copa" }
    ],
  },

    jugadores: {
      general: [
        { word: "Lionel Messi", hint: "Silencio" },
        { word: "Cristiano Ronaldo", hint: "Exigencia" },
        { word: "Kylian Mbappé", hint: "Explosión" },
        { word: "Erling Haaland", hint: "Imparable" },
        { word: "Kevin De Bruyne", hint: "Claridad" },
        { word: "Vinícius Jr.", hint: "Provoca" },
        { word: "Jude Bellingham", hint: "Llegada" },
        { word: "Neymar", hint: "Desequilibrio" },
        { word: "Mohamed Salah", hint: "Diagonal" },
        { word: "Luka Modrić", hint: "Elegancia" },
        { word: "Rodri", hint: "Equilibrio" },
        { word: "Bernardo Silva", hint: "Control" },
        { word: "Antoine Griezmann", hint: "Inteligencia" },
        { word: "Harry Kane", hint: "Lectura" },
        { word: "Federico Valverde", hint: "Pulmón" },
        { word: "Bukayo Saka", hint: "Constancia" },
        { word: "Victor Osimhen", hint: "Potencia" },
        { word: "Achraf Hakimi", hint: "Profundidad" },
        { word: "Bruno Fernandes", hint: "Riesgo" },
        { word: "Julian Álvarez", hint: "Oportunismo" },
        { word: "Messi", hint: "Tiempo" },
        { word: "Haaland", hint: "Área" },
        { word: "Modrić", hint: "Pausa" },
        { word: "Mbappé", hint: "Espalda" },
        { word: "Valverde", hint: "Ida y vuelta" },
        { word: "De Bruyne", hint: "Visión" },
        { word: "Vinícius", hint: "Atrevimiento" },
        { word: "Griezmann", hint: "Lectura" },
        { word: "Rodri", hint: "Orden" },
        { word: "Casemiro", hint: "Cobertura" },
        { word: "Joshua Kimmich", hint: "Equilibrio" },
        { word: "Frenkie de Jong", hint: "Conducción" },
        { word: "Ilkay Gündogan", hint: "Timing" },
        { word: "Bernardo Silva", hint: "Control" },
        { word: "Antoine Griezmann", hint: "Lectura" },
        { word: "Declan Rice", hint: "Sostén" },
        { word: "Pedri", hint: "Claridad" },
        { word: "Bruno Fernandes", hint: "Riesgo" },
        { word: "Vinícius Jr.", hint: "Atrevimiento" },
        { word: "Bukayo Saka", hint: "Constancia" },
        { word: "Rafael Leão", hint: "Zancada" },
        { word: "Luis Díaz", hint: "Intensidad" },
        { word: "Ousmane Dembélé", hint: "Caos" },
        { word: "Jadon Sancho", hint: "Fluidez" },
        { word: "Khvicha Kvaratskhelia", hint: "Imprevisible" },
        { word: "Federico Chiesa", hint: "Directo" },
        { word: "Jude Bellingham", hint: "Llegada" },
        { word: "Martin Ødegaard", hint: "Dirección" },
        { word: "Alexis Mac Allister", hint: "Equilibrio" },
        { word: "Enzo Fernández", hint: "Ritmo" },
        { word: "Gavi", hint: "Carácter" },
        { word: "Nicolò Barella", hint: "Motor" },
        { word: "Toni Kroos", hint: "Simpleza" },
        { word: "Marcelo Brozović", hint: "Brújula" },
        { word: "Virgil van Dijk", hint: "Autoridad" },
        { word: "Rúben Dias", hint: "Mando" },
        { word: "Ronald Araújo", hint: "Anticipación" },
        { word: "Matthijs de Ligt", hint: "Solidez" },
        { word: "William Saliba", hint: "Templanza" },
        { word: "Achraf Hakimi", hint: "Proyección" },
        { word: "Theo Hernández", hint: "Potencia" },
        { word: "João Cancelo", hint: "Creatividad" },
        { word: "Emiliano Martínez", hint: "Personalidad" },
        { word: "Thibaut Courtois", hint: "Envergadura" },
        { word: "Alisson", hint: "Seguridad" },
        { word: "Ederson", hint: "Inicio" },
        { word: "Marc-André ter Stegen", hint: "Calma" },
        { word: "Jan Oblak", hint: "Constancia" },
        { word: "James Rodríguez", hint: "Talento" },
        { word: "José María Giménez", hint: "Choque" },
        { word: "Giorgian De Arrascaeta", hint: "Creatividad" },
        { word: "Manuel Ugarte", hint: "Recuperación" },
        { word: "Facundo Pellistri", hint: "Velocidad" },
        { word: "Alexis Sánchez", hint: "Rebeldía" },
        { word: "Arturo Vidal", hint: "Carácter" },
        { word: "Ben Brereton", hint: "Energía" },
        { word: "Takefusa Kubo", hint: "Agilidad" },
        { word: "Kaoru Mitoma", hint: "Desborde" },
        { word: "Pelé", hint: "Eternidad" },
        { word: "Diego Maradona", hint: "Rebeldía" },
        { word: "Johan Cruyff", hint: "Revolución" },
        { word: "Franz Beckenbauer", hint: "Elegancia" },
        { word: "Alfredo Di Stéfano", hint: "Totalidad" },
        { word: "Michel Platini", hint: "Influencia" },
        { word: "Zinedine Zidane", hint: "Templanza" },
        { word: "Mario Kempes", hint: "Decisión" },
        { word: "Daniel Passarella", hint: "Autoridad" },
        { word: "Gabriel Batistuta", hint: "Determinación" },
        { word: "Juan Román Riquelme", hint: "Pausa" },
        { word: "Javier Zanetti", hint: "Constancia" },
        { word: "Carlos Tevez", hint: "Coraje" },
        { word: "Ronaldo Nazário", hint: "Explosión" },
        { word: "Ronaldinho", hint: "Alegría" },
        { word: "Romário", hint: "Instinto" },
        { word: "Zico", hint: "Maestría" },
        { word: "Cafu", hint: "Recorrido" },
        { word: "Obdulio Varela", hint: "Liderazgo" },
        { word: "Enzo Francescoli", hint: "Distinción" },
        { word: "Diego Forlán", hint: "Precisión" },
        { word: "Héctor Scarone", hint: "Influencia" },
        { word: "Paolo Maldini", hint: "Corrección" },
        { word: "Franco Baresi", hint: "Lectura" },
        { word: "Roberto Baggio", hint: "Sensibilidad" },
        { word: "Andrea Pirlo", hint: "Claridad" },
        { word: "Gerd Müller", hint: "Eficacia" },
        { word: "Lothar Matthäus", hint: "Presencia" },
        { word: "Miroslav Klose", hint: "Oportunismo" },
        { word: "Xavi Hernández", hint: "Ritmo" },
        { word: "Andrés Iniesta", hint: "Intuición" },
        { word: "Iker Casillas", hint: "Instante" },
        { word: "Thierry Henry", hint: "Fluidez" },
        { word: "Michael Laudrup", hint: "Visión" },
        { word: "Dennis Bergkamp", hint: "Control" },
        { word: "Sócrates", hint: "Pensamiento" },
        { word: "Bobby Charlton", hint: "Equilibrio" },
        { word: "George Best", hint: "Carisma" },
        { word: "Lev Yashin", hint: "Reflejos" },
        { word: "Eusébio", hint: "Potencia" },
        { word: "Hugo Sánchez", hint: "Acrobacia" },
        { word: "Carlos Valderrama", hint: "Personalidad" },  
        { word: "Ruud Gullit", hint: "Versatilidad" },
        { word: "Marco van Basten", hint: "Pureza" },
        { word: "Clarence Seedorf", hint: "Equilibrio" },
        { word: "Frank Rijkaard", hint: "Orden" },
        { word: "Baresi", hint: "Anticipación" },
        { word: "Schmeichel", hint: "Autoridad" },
        { word: "Hristo Stoichkov", hint: "Carácter" },
        { word: "Rivaldo", hint: "Resolución" },
        { word: "Kaká", hint: "Verticalidad" },
        { word: "Karim Benzema", hint: "Conexión" },
        { word: "Son Heung-min", hint: "Silencio" },
        { word: "Marcus Rashford", hint: "Vertical" },
        { word: "Lautaro Martínez", hint: "Agresividad" },
        { word: "Paulo Dybala", hint: "Fragilidad" },
        { word: "Ángel Di María", hint: "Zurda" },
        { word: "Rodrygo", hint: "Momento" },
        { word: "Gabriel Jesus", hint: "Presión" },
        { word: "Darwin Núñez", hint: "Impulso" },
        { word: "João Félix", hint: "Intermitencia" },
        { word: "Rasmus Højlund", hint: "Ansiedad" },
        { word: "Victor Boniface", hint: "Presencia" },
        { word: "Alexander Isak", hint: "Elasticidad" },
        { word: "Dusan Vlahović", hint: "Fijeza" },
        { word: "Phil Foden", hint: "Lectura" },
        { word: "Jack Grealish", hint: "Ritmo" },
        { word: "Cole Palmer", hint: "Frialdad" },
        { word: "Jamal Musiala", hint: "Fluidez" },
        { word: "Florian Wirtz", hint: "Clarividencia" },
        { word: "Eduardo Camavinga", hint: "Adaptación" },
        { word: "Aurélien Tchouamենի", hint: "Cobertura" },
        { word: "Declan Rice", hint: "Sostén" },
        { word: "Moisés Caicedo", hint: "Pulso" },
        { word: "Bruno Guimarães", hint: "Orden" },
        { word: "Cristian Romero", hint: "Límite" },
        { word: "Éder Militão", hint: "Reacción" },
        { word: "Jules Koundé", hint: "Versatilidad" },
        { word: "Lisandro Martínez", hint: "Coraje" },
        { word: "Kim Min-jae", hint: "Fuerza" },
        { word: "Alejandro Balde", hint: "Proyección" },
        { word: "Jeremie Frimpong", hint: "Velocidad" },
        { word: "Reece James", hint: "Potencia" },
        { word: "Trent Alexander-Arnold", hint: "Precisión" },
        { word: "Mike Maignan", hint: "Reflejos" },
        { word: "Gianluigi Donnarumma", hint: "Dimensión" },
        { word: "André Onana", hint: "Riesgo" },
        { word: "David Raya", hint: "Salida" },
        { word: "Endrick", hint: "Expectativa" },
        { word: "Lamine Yamal", hint: "Desparpajo" },
        { word: "Estevão", hint: "Promesa" },
        { word: "Arda Güler", hint: "Delicadeza" },
        { word: "Takehiro Tomiyasu", hint: "Disciplina" },
        { word: "Mehdi Taremi", hint: "Persistencia" },
        { word: "Achraf Dari", hint: "Anticipo" },
        { word: "Sergej Milinković-Savić", hint: "Peso" }
      ],
      actuales: [
        { word: "Lionel Messi", hint: "Silencio" },
        { word: "Cristiano Ronaldo", hint: "Exigencia" },
        { word: "Kylian Mbappé", hint: "Explosión" },
        { word: "Erling Haaland", hint: "Imparable" },
        { word: "Kevin De Bruyne", hint: "Claridad" },
        { word: "Vinícius Jr.", hint: "Provoca" },
        { word: "Jude Bellingham", hint: "Llegada" },
        { word: "Neymar", hint: "Desequilibrio" },
        { word: "Mohamed Salah", hint: "Diagonal" },
        { word: "Luka Modrić", hint: "Elegancia" },
        { word: "Rodri", hint: "Equilibrio" },
        { word: "Bernardo Silva", hint: "Control" },
        { word: "Antoine Griezmann", hint: "Inteligencia" },
        { word: "Harry Kane", hint: "Lectura" },
        { word: "Federico Valverde", hint: "Pulmón" },
        { word: "Bukayo Saka", hint: "Constancia" },
        { word: "Victor Osimhen", hint: "Potencia" },
        { word: "Achraf Hakimi", hint: "Profundidad" },
        { word: "Bruno Fernandes", hint: "Riesgo" },
        { word: "Julian Álvarez", hint: "Oportunismo" },
        { word: "Messi", hint: "Tiempo" },
        { word: "Haaland", hint: "Área" },
        { word: "Modrić", hint: "Pausa" },
        { word: "Mbappé", hint: "Espalda" },
        { word: "Valverde", hint: "Ida y vuelta" },
        { word: "De Bruyne", hint: "Visión" },
        { word: "Vinícius", hint: "Atrevimiento" },
        { word: "Griezmann", hint: "Lectura" },
        { word: "Rodri", hint: "Orden" },
        { word: "Casemiro", hint: "Cobertura" },
        { word: "Joshua Kimmich", hint: "Equilibrio" },
        { word: "Frenkie de Jong", hint: "Conducción" },
        { word: "Ilkay Gündogan", hint: "Timing" },
        { word: "Bernardo Silva", hint: "Control" },
        { word: "Antoine Griezmann", hint: "Lectura" },
        { word: "Declan Rice", hint: "Sostén" },
        { word: "Pedri", hint: "Claridad" },
        { word: "Bruno Fernandes", hint: "Riesgo" },
        { word: "Vinícius Jr.", hint: "Atrevimiento" },
        { word: "Bukayo Saka", hint: "Constancia" },
        { word: "Rafael Leão", hint: "Zancada" },
        { word: "Luis Díaz", hint: "Intensidad" },
        { word: "Ousmane Dembélé", hint: "Caos" },
        { word: "Jadon Sancho", hint: "Fluidez" },
        { word: "Khvicha Kvaratskhelia", hint: "Imprevisible" },
        { word: "Federico Chiesa", hint: "Directo" },
        { word: "Jude Bellingham", hint: "Llegada" },
        { word: "Martin Ødegaard", hint: "Dirección" },
        { word: "Alexis Mac Allister", hint: "Equilibrio" },
        { word: "Enzo Fernández", hint: "Ritmo" },
        { word: "Gavi", hint: "Carácter" },
        { word: "Nicolò Barella", hint: "Motor" },
        { word: "Toni Kroos", hint: "Simpleza" },
        { word: "Marcelo Brozović", hint: "Brújula" },
        { word: "Virgil van Dijk", hint: "Autoridad" },
        { word: "Rúben Dias", hint: "Mando" },
        { word: "Ronald Araújo", hint: "Anticipación" },
        { word: "Matthijs de Ligt", hint: "Solidez" },
        { word: "William Saliba", hint: "Templanza" },
        { word: "Achraf Hakimi", hint: "Proyección" },
        { word: "Theo Hernández", hint: "Potencia" },
        { word: "João Cancelo", hint: "Creatividad" },
        { word: "Emiliano Martínez", hint: "Personalidad" },
        { word: "Thibaut Courtois", hint: "Envergadura" },
        { word: "Alisson", hint: "Seguridad" },
        { word: "Ederson", hint: "Inicio" },
        { word: "Marc-André ter Stegen", hint: "Calma" },
        { word: "Jan Oblak", hint: "Constancia" },
        { word: "James Rodríguez", hint: "Talento" },
        { word: "José María Giménez", hint: "Choque" },
        { word: "Giorgian De Arrascaeta", hint: "Creatividad" },
        { word: "Manuel Ugarte", hint: "Recuperación" },
        { word: "Facundo Pellistri", hint: "Velocidad" },
        { word: "Alexis Sánchez", hint: "Rebeldía" },
        { word: "Arturo Vidal", hint: "Carácter" },
        { word: "Ben Brereton", hint: "Energía" },
        { word: "Takefusa Kubo", hint: "Agilidad" },
        { word: "Kaoru Mitoma", hint: "Desborde" },
        { word: "Robert Lewandowski", hint: "Instinto" },
        { word: "Karim Benzema", hint: "Conexión" },
        { word: "Son Heung-min", hint: "Silencio" },
        { word: "Marcus Rashford", hint: "Vertical" },
        { word: "Lautaro Martínez", hint: "Agresividad" },
        { word: "Paulo Dybala", hint: "Fragilidad" },
        { word: "Ángel Di María", hint: "Zurda" },
        { word: "Rodrygo", hint: "Momento" },
        { word: "Gabriel Jesus", hint: "Presión" },
        { word: "Darwin Núñez", hint: "Impulso" },
        { word: "João Félix", hint: "Intermitencia" },
        { word: "Rasmus Højlund", hint: "Ansiedad" },
        { word: "Victor Boniface", hint: "Presencia" },
        { word: "Alexander Isak", hint: "Elasticidad" },
        { word: "Dusan Vlahović", hint: "Fijeza" },
        { word: "Phil Foden", hint: "Lectura" },
        { word: "Jack Grealish", hint: "Ritmo" },
        { word: "Cole Palmer", hint: "Frialdad" },
        { word: "Jamal Musiala", hint: "Fluidez" },
        { word: "Florian Wirtz", hint: "Clarividencia" },
        { word: "Eduardo Camavinga", hint: "Adaptación" },
        { word: "Aurélien Tchouamենի", hint: "Cobertura" },
        { word: "Declan Rice", hint: "Sostén" },
        { word: "Moisés Caicedo", hint: "Pulso" },
        { word: "Bruno Guimarães", hint: "Orden" },
        { word: "Cristian Romero", hint: "Límite" },
        { word: "Éder Militão", hint: "Reacción" },
        { word: "Jules Koundé", hint: "Versatilidad" },
        { word: "Lisandro Martínez", hint: "Coraje" },
        { word: "Kim Min-jae", hint: "Fuerza" },
        { word: "Alejandro Balde", hint: "Proyección" },
        { word: "Jeremie Frimpong", hint: "Velocidad" },
        { word: "Reece James", hint: "Potencia" },
        { word: "Trent Alexander-Arnold", hint: "Precisión" },
        { word: "Mike Maignan", hint: "Reflejos" },
        { word: "Gianluigi Donnarumma", hint: "Dimensión" },
        { word: "André Onana", hint: "Riesgo" },
        { word: "David Raya", hint: "Salida" },
        { word: "Endrick", hint: "Expectativa" },
        { word: "Lamine Yamal", hint: "Desparpajo" },
        { word: "Estevão", hint: "Promesa" },
        { word: "Arda Güler", hint: "Delicadeza" },
        { word: "Takehiro Tomiyasu", hint: "Disciplina" },
        { word: "Mehdi Taremi", hint: "Persistencia" },
        { word: "Achraf Dari", hint: "Anticipo" },
        { word: "Sergej Milinković-Savić", hint: "Peso" }
      ],
      historicos: [
        { word: "Pelé", hint: "Eternidad" },
        { word: "Diego Maradona", hint: "Rebeldía" },
        { word: "Johan Cruyff", hint: "Revolución" },
        { word: "Franz Beckenbauer", hint: "Elegancia" },
        { word: "Alfredo Di Stéfano", hint: "Totalidad" },
        { word: "Michel Platini", hint: "Influencia" },
        { word: "Zinedine Zidane", hint: "Templanza" },
        { word: "Mario Kempes", hint: "Decisión" },
        { word: "Daniel Passarella", hint: "Autoridad" },
        { word: "Gabriel Batistuta", hint: "Determinación" },
        { word: "Juan Román Riquelme", hint: "Pausa" },
        { word: "Javier Zanetti", hint: "Constancia" },
        { word: "Carlos Tevez", hint: "Coraje" },
        { word: "Ronaldo Nazário", hint: "Explosión" },
        { word: "Ronaldinho", hint: "Alegría" },
        { word: "Romário", hint: "Instinto" },
        { word: "Zico", hint: "Maestría" },
        { word: "Cafu", hint: "Recorrido" },
        { word: "Obdulio Varela", hint: "Liderazgo" },
        { word: "Enzo Francescoli", hint: "Distinción" },
        { word: "Diego Forlán", hint: "Precisión" },
        { word: "Héctor Scarone", hint: "Influencia" },
        { word: "Paolo Maldini", hint: "Corrección" },
        { word: "Franco Baresi", hint: "Lectura" },
        { word: "Roberto Baggio", hint: "Sensibilidad" },
        { word: "Andrea Pirlo", hint: "Claridad" },
        { word: "Gerd Müller", hint: "Eficacia" },
        { word: "Lothar Matthäus", hint: "Presencia" },
        { word: "Miroslav Klose", hint: "Oportunismo" },
        { word: "Xavi Hernández", hint: "Ritmo" },
        { word: "Andrés Iniesta", hint: "Intuición" },
        { word: "Iker Casillas", hint: "Instante" },
        { word: "Thierry Henry", hint: "Fluidez" },
        { word: "Michael Laudrup", hint: "Visión" },
        { word: "Dennis Bergkamp", hint: "Control" },
        { word: "Sócrates", hint: "Pensamiento" },
        { word: "Bobby Charlton", hint: "Equilibrio" },
        { word: "George Best", hint: "Carisma" },
        { word: "Lev Yashin", hint: "Reflejos" },
        { word: "Eusébio", hint: "Potencia" },
        { word: "Hugo Sánchez", hint: "Acrobacia" },
        { word: "Carlos Valderrama", hint: "Personalidad" },  
        { word: "Ruud Gullit", hint: "Versatilidad" },
        { word: "Marco van Basten", hint: "Pureza" },
        { word: "Clarence Seedorf", hint: "Equilibrio" },
        { word: "Frank Rijkaard", hint: "Orden" },
        { word: "Baresi", hint: "Anticipación" },
        { word: "Schmeichel", hint: "Autoridad" },
        { word: "Hristo Stoichkov", hint: "Carácter" },
        { word: "Rivaldo", hint: "Resolución" },
        { word: "Kaká", hint: "Verticalidad" }
      ],
    },
    clubes: {
      general: [
        { word: "Real Madrid", hint: "Eternidad" },
        { word: "Barcelona", hint: "Idea" },
        { word: "Atlético Madrid", hint: "Resistencia" },
        { word: "Sevilla", hint: "Especialista" },
        { word: "Valencia", hint: "Caída" },
        { word: "Villarreal", hint: "Inteligencia" },
        { word: "Real Sociedad", hint: "Orden" },
        { word: "Athletic Club", hint: "Raíces" },
        { word: "Manchester United", hint: "Pasado" },
        { word: "Manchester City", hint: "Control" },
        { word: "Liverpool", hint: "Empuje" },
        { word: "Chelsea", hint: "Inestabilidad" },
        { word: "Arsenal", hint: "Proceso" },
        { word: "Tottenham", hint: "Intención" },
        { word: "Newcastle", hint: "Renacer" },
        { word: "Aston Villa", hint: "Regreso" },
        { word: "Bayern Múnich", hint: "Dominio" },
        { word: "Borussia Dortmund", hint: "Impulso" },
        { word: "RB Leipzig", hint: "Sistema" },
        { word: "Bayer Leverkusen", hint: "Paciencia" },
        { word: "Juventus", hint: "Sobriedad" },
        { word: "AC Milan", hint: "Memoria" },
        { word: "Inter", hint: "Equilibrio" },
        { word: "Napoli", hint: "Pasión" },
        { word: "Roma", hint: "Orgullo" },
        { word: "Lazio", hint: "Tensión" },
        { word: "Atalanta", hint: "Atrevimiento" },
        { word: "Paris Saint-Germain", hint: "Lujo" },
        { word: "Monaco", hint: "Talento" },
        { word: "Lyon", hint: "Formación" },
        { word: "Ajax", hint: "Escuela" },
        { word: "PSV", hint: "Continuidad" },
        { word: "Feyenoord", hint: "Empuje" },
        { word: "Benfica", hint: "Cantera" },
        { word: "Porto", hint: "Astucia" },
        { word: "Sporting", hint: "Paciencia" },
        { word: "Celtic", hint: "Fervor" },
        { word: "Rangers", hint: "Identidad" },
        { word: "Boca Juniors", hint: "Presión" },
        { word: "River Plate", hint: "Fluidez" },
        { word: "Independiente", hint: "Copas" },
        { word: "Racing Club", hint: "Expectativa" },
        { word: "San Lorenzo", hint: "Sacrificio" },
        { word: "Vélez Sarsfield", hint: "Método" },
        { word: "Estudiantes", hint: "Disciplina" },
        { word: "Newell's", hint: "Identidad" },
        { word: "Rosario Central", hint: "Euforia" },
        { word: "Lanús", hint: "Gestión" },
        { word: "Argentinos Juniors", hint: "Semillero" },
        { word: "Huracán", hint: "Romanticismo" },
        { word: "Flamengo", hint: "Multitud" },
        { word: "Palmeiras", hint: "Estructura" },
        { word: "Corinthians", hint: "Presión" },
        { word: "São Paulo", hint: "Peso" },
        { word: "Santos", hint: "Origen" },
        { word: "Grêmio", hint: "Carácter" },
        { word: "Internacional", hint: "Rivalidad" },
        { word: "Atlético Mineiro", hint: "Impulso" },
        { word: "Peñarol", hint: "Garra" },
        { word: "Nacional", hint: "Tradición" },
        { word: "Defensor Sporting", hint: "Formación" },
        { word: "Colo-Colo", hint: "Orgullo" },
        { word: "Universidad de Chile", hint: "Pasión" },
        { word: "Universidad Católica", hint: "Orden" },
        { word: "Atlético Nacional", hint: "Identidad" },
        { word: "Millonarios", hint: "Historia" },
        { word: "Junior", hint: "Intensidad" },
        { word: "Liga de Quito", hint: "Altura" },
        { word: "Independiente del Valle", hint: "Proyecto" },
        { word: "Barcelona SC", hint: "Popularidad" },
        { word: "Olimpia", hint: "Respeto" },
        { word: "Cerro Porteño", hint: "Presión" },
        { word: "Bolívar", hint: "Condición" },
        { word: "The Strongest", hint: "Fortaleza" },
        { word: "América de Cali", hint: "Persistencia" },
        { word: "Once Caldas", hint: "Sorpresa" },
        { word: "Al Ahly", hint: "Dominio" },
        { word: "Al Hilal", hint: "Ambición" },
        { word: "Al Nassr", hint: "Impacto" },
        { word: "Al Ittihad", hint: "Historia" },
        { word: "Urawa Red Diamonds", hint: "Disciplina" },
        { word: "Kashima Antlers", hint: "Orden" },
        { word: "Yokohama F. Marinos", hint: "Ritmo" },
        { word: "Gamba Osaka", hint: "Sistema" },
        { word: "Monterrey", hint: "Estructura" },
        { word: "Club América", hint: "Exigencia" },
        { word: "Chivas", hint: "Identidad" },
        { word: "Tigres", hint: "Potencia" },
        { word: "Cruz Azul", hint: "Esperanza" },
        { word: "Toluca", hint: "Continuidad" },
        { word: "Pumas", hint: "Juventud" },
        { word: "LA Galaxy", hint: "Marca" },
        { word: "Inter Miami", hint: "Repercusión" },
        { word: "Seattle Sounders", hint: "Constancia" },
        { word: "Atlanta United", hint: "Expansión" },
        { word: "Toronto FC", hint: "Proyecto" },
        { word: "Wydad Casablanca", hint: "Empuje" },
        { word: "Esperance Tunis", hint: "Resistencia" },
        { word: "Kaizer Chiefs", hint: "Popularidad" },
        { word: "Mamelodi Sundowns", hint: "Control" },
        { word: "Auckland City", hint: "Hegemonía" },
        { word: "Sydney FC", hint: "Orden" },
        { word: "Melbourne Victory", hint: "Ambición" },
        { word: "Shanghai Port", hint: "Inversión" }
      ],
      europeos: [
        { word: "Real Madrid", hint: "Eternidad" },
        { word: "Barcelona", hint: "Idea" },
        { word: "Atlético Madrid", hint: "Resistencia" },
        { word: "Sevilla", hint: "Especialista" },
        { word: "Valencia", hint: "Caída" },
        { word: "Villarreal", hint: "Inteligencia" },
        { word: "Real Sociedad", hint: "Orden" },
        { word: "Athletic Club", hint: "Raíces" },
        { word: "Manchester United", hint: "Pasado" },
        { word: "Manchester City", hint: "Control" },
        { word: "Liverpool", hint: "Empuje" },
        { word: "Chelsea", hint: "Inestabilidad" },
        { word: "Arsenal", hint: "Proceso" },
        { word: "Tottenham", hint: "Intención" },
        { word: "Newcastle", hint: "Renacer" },
        { word: "Aston Villa", hint: "Regreso" },
        { word: "Bayern Múnich", hint: "Dominio" },
        { word: "Borussia Dortmund", hint: "Impulso" },
        { word: "RB Leipzig", hint: "Sistema" },
        { word: "Bayer Leverkusen", hint: "Paciencia" },
        { word: "Juventus", hint: "Sobriedad" },
        { word: "AC Milan", hint: "Memoria" },
        { word: "Inter", hint: "Equilibrio" },
        { word: "Napoli", hint: "Pasión" },
        { word: "Roma", hint: "Orgullo" },
        { word: "Lazio", hint: "Tensión" },
        { word: "Atalanta", hint: "Atrevimiento" },
        { word: "Paris Saint-Germain", hint: "Lujo" },
        { word: "Monaco", hint: "Talento" },
        { word: "Lyon", hint: "Formación" },
        { word: "Ajax", hint: "Escuela" },
        { word: "PSV", hint: "Continuidad" },
        { word: "Feyenoord", hint: "Empuje" },
        { word: "Benfica", hint: "Cantera" },
        { word: "Porto", hint: "Astucia" },
        { word: "Sporting", hint: "Paciencia" },
        { word: "Celtic", hint: "Fervor" },
        { word: "Rangers", hint: "Identidad" }
      ],
      sudamericanos: [
        { word: "Boca Juniors", hint: "Presión" },
        { word: "River Plate", hint: "Fluidez" },
        { word: "Independiente", hint: "Copas" },
        { word: "Racing Club", hint: "Expectativa" },
        { word: "San Lorenzo", hint: "Sacrificio" },
        { word: "Vélez Sarsfield", hint: "Método" },
        { word: "Estudiantes", hint: "Disciplina" },
        { word: "Newell's", hint: "Identidad" },
        { word: "Rosario Central", hint: "Euforia" },
        { word: "Lanús", hint: "Gestión" },
        { word: "Argentinos Juniors", hint: "Semillero" },
        { word: "Huracán", hint: "Romanticismo" },
        { word: "Flamengo", hint: "Multitud" },
        { word: "Palmeiras", hint: "Estructura" },
        { word: "Corinthians", hint: "Presión" },
        { word: "São Paulo", hint: "Peso" },
        { word: "Santos", hint: "Origen" },
        { word: "Grêmio", hint: "Carácter" },
        { word: "Internacional", hint: "Rivalidad" },
        { word: "Atlético Mineiro", hint: "Impulso" },
        { word: "Peñarol", hint: "Garra" },
        { word: "Nacional", hint: "Tradición" },
        { word: "Defensor Sporting", hint: "Formación" },
        { word: "Colo-Colo", hint: "Orgullo" },
        { word: "Universidad de Chile", hint: "Pasión" },
        { word: "Universidad Católica", hint: "Orden" },
        { word: "Atlético Nacional", hint: "Identidad" },
        { word: "Millonarios", hint: "Historia" },
        { word: "Junior", hint: "Intensidad" },
        { word: "Liga de Quito", hint: "Altura" },
        { word: "Independiente del Valle", hint: "Proyecto" },
        { word: "Barcelona SC", hint: "Popularidad" },
        { word: "Olimpia", hint: "Respeto" },
        { word: "Cerro Porteño", hint: "Presión" },
        { word: "Bolívar", hint: "Condición" },
        { word: "The Strongest", hint: "Fortaleza" },
        { word: "América de Cali", hint: "Persistencia" },
        { word: "Once Caldas", hint: "Sorpresa" }
      ],

      restoDelMundo: [
        { word: "Al Ahly", hint: "Dominio" },
        { word: "Al Hilal", hint: "Ambición" },
        { word: "Al Nassr", hint: "Impacto" },
        { word: "Al Ittihad", hint: "Historia" },
        { word: "Urawa Red Diamonds", hint: "Disciplina" },
        { word: "Kashima Antlers", hint: "Orden" },
        { word: "Yokohama F. Marinos", hint: "Ritmo" },
        { word: "Gamba Osaka", hint: "Sistema" },
        { word: "Monterrey", hint: "Estructura" },
        { word: "Club América", hint: "Exigencia" },
        { word: "Chivas", hint: "Identidad" },
        { word: "Tigres", hint: "Potencia" },
        { word: "Cruz Azul", hint: "Esperanza" },
        { word: "Toluca", hint: "Continuidad" },
        { word: "Pumas", hint: "Juventud" },
        { word: "LA Galaxy", hint: "Marca" },
        { word: "Inter Miami", hint: "Repercusión" },
        { word: "Seattle Sounders", hint: "Constancia" },
        { word: "Atlanta United", hint: "Expansión" },
        { word: "Toronto FC", hint: "Proyecto" },
        { word: "Wydad Casablanca", hint: "Empuje" },
        { word: "Esperance Tunis", hint: "Resistencia" },
        { word: "Kaizer Chiefs", hint: "Popularidad" },
        { word: "Mamelodi Sundowns", hint: "Control" },
        { word: "Auckland City", hint: "Hegemonía" },
        { word: "Sydney FC", hint: "Orden" },
        { word: "Melbourne Victory", hint: "Ambición" },
        { word: "Shanghai Port", hint: "Inversión" },
      ],
    },
    trofeos: {
      general: [
        { word: "Copa del Mundo", hint: "Eternidad" },
        { word: "Champions League", hint: "Cima" },
        { word: "Europa League", hint: "Oportunidad" },
        { word: "Conference League", hint: "Escalón" },
        { word: "Copa América", hint: "Continente" },
        { word: "Eurocopa", hint: "Identidad" },
        { word: "Copa Africana de Naciones", hint: "Orgullo" },
        { word: "Copa Asiática", hint: "Proceso" },
        { word: "Copa Oro", hint: "Región" },
        { word: "Copa Confederaciones", hint: "Puente" },
        { word: "Copa Libertadores", hint: "Mística" },
        { word: "Copa Sudamericana", hint: "Revancha" },
        { word: "Recopa Sudamericana", hint: "Duelo" },
        { word: "Copa Intercontinental", hint: "Choque" },
        { word: "Mundial de Clubes", hint: "Choque" },
        { word: "Supercopa de Europa", hint: "Pulso" },
        { word: "Supercopa Sudamericana", hint: "Comparación" },
        { word: "FA Cup", hint: "Tradición" },
        { word: "Copa del Rey", hint: "Historia" },
        { word: "Coppa Italia", hint: "Ritual" },
        { word: "DFB-Pokal", hint: "Interrupción" },
        { word: "Coupe de France", hint: "Sorpresa" },
        { word: "Premier League", hint: "Exigencia" },
        { word: "LaLiga", hint: "Narrativa" },
        { word: "Serie A", hint: "Táctica" },
        { word: "Bundesliga", hint: "Ritmo" },
        { word: "Ligue 1", hint: "Control" },
        { word: "Brasileirão", hint: "Resistencia" },
        { word: "Liga Profesional Argentina", hint: "Presión" },
        { word: "Uruguayo", hint: "Tradición" },
        { word: "Liga MX", hint: "Caos" },
        { word: "MLS Cup", hint: "Expansión" },
        { word: "Balón de Oro", hint: "Consagración" },
        { word: "The Best", hint: "Momento" },
        { word: "Bota de Oro", hint: "Instinto" },
        { word: "Guante de Oro", hint: "Reflejos" },
        { word: "Golden Boy", hint: "Promesa" },
        { word: "Pichichi", hint: "Constancia" },
        { word: "Capocannoniere", hint: "Regularidad" },
        { word: "Máximo Goleador Mundial", hint: "Persistencia" },
      ],
    },
    partidos: {
      general: [
        { word: "Maracanazo 1950", hint: "Silencio" },
        { word: "Final Mundial 1986", hint: "Destino" },
        { word: "Final Mundial 1970", hint: "Obra" },
        { word: "Final Mundial 2014", hint: "Espera" },
        { word: "Final Mundial 2022", hint: "Catarsis" },
        { word: "Argentina vs Inglaterra 1986", hint: "Contraste" },
        { word: "Brasil vs Italia 1970", hint: "Consagración" },
        { word: "Alemania vs Brasil 2014", hint: "Incredulidad" },
        { word: "Italia vs Francia 2006", hint: "Impulso" },
        { word: "España vs Países Bajos 2010", hint: "Paciencia" },
        { word: "Final Champions 1999", hint: "Instante" },
        { word: "Final Champions 2005", hint: "Resurrección" },
        { word: "Final Champions 2012", hint: "Crueldad" },
        { word: "Final Champions 2022", hint: "Control" },
        { word: "Barcelona vs PSG 2017", hint: "Imposible" },
        { word: "Liverpool vs Milan 2005", hint: "Fe" },
        { word: "Real Madrid vs Atlético 2014", hint: "Persistencia" },
        { word: "Real Madrid vs Juventus 2018", hint: "Suspensión" },
        { word: "Argentina vs Francia 2018", hint: "Caos" },
        { word: "Argentina vs Francia 2022", hint: "Eternidad" },
        { word: "Brasil vs Uruguay 1950", hint: "Trauma" },
        { word: "Uruguay vs Brasil 1950", hint: "Osadía" },
        { word: "Chile vs Argentina 2015", hint: "Repetición" },
        { word: "Chile vs Argentina 2016", hint: "Persistencia" },
        { word: "Boca vs River 2018", hint: "Desborde" },
        { word: "River vs Boca 2018", hint: "Revancha" },
        { word: "Peñarol vs Real Madrid 1966", hint: "Orgullo" },
        { word: "Nacional vs Estudiantes 1971", hint: "Choque" },
        { word: "Manchester United vs Bayern 1999", hint: "Minutos" },
        { word: "Chelsea vs Bayern 2012", hint: "Resistencia" },
        { word: "Ajax vs Milan 1995", hint: "Juventud" },
        { word: "Holanda vs Alemania 1974", hint: "Estilo" },
        { word: "Brasil vs Francia 1998", hint: "Desconcierto" },
        { word: "Alemania vs Argentina 1990", hint: "Precisión" },
        { word: "España vs Italia 2012", hint: "Superioridad" },
        { word: "Portugal vs Francia 2016", hint: "Aguante" },
        { word: "Inglaterra vs Alemania 1966", hint: "Duda" },
        { word: "Italia vs Brasil 1982", hint: "Eficacia" },
        { word: "Argentina vs Holanda 1978", hint: "Presión" },
        { word: "Uruguay vs Argentina 1930", hint: "Inicio" }
      ],    
    },
    selecciones: {
        general: [
        { word: "Brasil", hint: "Alegría" },
          { word: "Argentina", hint: "Pasión" },
          { word: "Uruguay", hint: "Carácter" },
          { word: "Alemania", hint: "Precisión" },
          { word: "Italia", hint: "Resistencia" },
          { word: "Francia", hint: "Potencia" },
          { word: "España", hint: "Control" },
          { word: "Inglaterra", hint: "Tradición" },
          { word: "Portugal", hint: "Esperar" },
          { word: "Países Bajos", hint: "Forma" },
          { word: "Croacia", hint: "Persistencia" },
          { word: "Bélgica", hint: "Talento" },
          { word: "México", hint: "Presión" },
          { word: "Colombia", hint: "Ritmo" },
          { word: "Chile", hint: "Intensidad" },
          { word: "Perú", hint: "Memoria" },
          { word: "Ecuador", hint: "Altura" },
          { word: "Paraguay", hint: "Fuerza" },
          { word: "Bolivia", hint: "Condición" },
          { word: "Venezuela", hint: "Evolución" },
          { word: "Estados Unidos", hint: "Orden" },
          { word: "Canadá", hint: "Crecimiento" },
          { word: "Costa Rica", hint: "Disciplina" },
          { word: "Honduras", hint: "Choque" },
          { word: "Panamá", hint: "Orgullo" },
          { word: "Jamaica", hint: "Velocidad" },
          { word: "Japón", hint: "Aplicación" },
          { word: "Corea del Sur", hint: "Energía" },
          { word: "Australia", hint: "Sacrificio" },
          { word: "Irán", hint: "Estructura" },
          { word: "Arabia Saudita", hint: "Atrevimiento" },
          { word: "Qatar", hint: "Proceso" },
          { word: "Nigeria", hint: "Físico" },
          { word: "Senegal", hint: "Potencia" },
          { word: "Marruecos", hint: "Convicción" },
          { word: "Camerún", hint: "Explosión" },
          { word: "Ghana", hint: "Coraje" },
          { word: "Egipto", hint: "Historia" },
          { word: "Dinamarca", hint: "Colectivo" },
          { word: "Suecia", hint: "Solidez" },
          { word: "Noruega", hint: "Paciencia" },
          { word: "Suiza", hint: "Equilibrio" },
          { word: "Polonia", hint: "Lucha" },
          { word: "Serbia", hint: "Intensidad" },
          { word: "República Checa", hint: "Orden" },
          { word: "Escocia", hint: "Orgullo" },
          { word: "Gales", hint: "Carácter" },
          { word: "Irlanda", hint: "Entrega" },
          { word: "Austria", hint: "Rigor" },
          { word: "Grecia", hint: "Cálculo" },
          { word: "Turquía", hint: "Impulso" },
          { word: "Ucrania", hint: "Resistencia" },
          { word: "Rusia", hint: "Bloque" },
          { word: "China", hint: "Expectativa" },
          { word: "India", hint: "Potencial" },
          { word: "Nueva Zelanda", hint: "Aislamiento" }
        ],
      },
  mundiales: {
      general: [
        { word: "Catar 2022", hint: "Desierto" },
        { word: "Rusia 2018", hint: "Moscú" },
        { word: "Brasil 2014", hint: "Samba" },
        { word: "Sudáfrica 2010", hint: "León" },
        { word: "Alemania 2006", hint: "Oktoberfest" },
        { word: "Japón-Corea 2002", hint: "Sushi" },
        { word: "Francia 1998", hint: "Torre" },
        { word: "Estados Unidos 1994", hint: "Estrellas" },
        { word: "Italia 1990", hint: "Pizza" },
        { word: "México 1986", hint: "Tacos" },
        { word: "España 1982", hint: "Paella" },
        { word: "Argentina 1978", hint: "Asado" },
        { word: "Alemania 1974", hint: "Bier" },
        { word: "México 1970", hint: "Sombrero" },
        { word: "Inglaterra 1966", hint: "Rey" },
        { word: "Chile 1962", hint: "Andes" },
        { word: "Suecia 1958", hint: "Vikingos" },
        { word: "Suiza 1954", hint: "Reloj" },
        { word: "Brasil 1950", hint: "Carnaval" },
        { word: "Italia 1934", hint: "Fascismo" },
        { word: "Uruguay 1930", hint: "Celeste" },
      ],    
    },

    dts: {
      general: [
        { word: "Pep Guardiola", hint: "Idea" },
        { word: "Jürgen Klopp", hint: "Energía" },
        { word: "Carlo Ancelotti", hint: "Gestión" },
        { word: "José Mourinho", hint: "Confrontación" },
        { word: "Diego Simeone", hint: "Intensidad" },
        { word: "Marcelo Bielsa", hint: "Convicción" },
        { word: "Zinedine Zidane", hint: "Templanza" },
        { word: "Luis Enrique", hint: "Valentía" },
        { word: "Xavi Hernández", hint: "Identidad" },
        { word: "Mikel Arteta", hint: "Construcción" },
        { word: "Erik ten Hag", hint: "Estructura" },
        { word: "Thomas Tuchel", hint: "Ajuste" },
        { word: "Julian Nagelsmann", hint: "Innovación" },
        { word: "Unai Emery", hint: "Detalle" },
        { word: "Mauricio Pochettino", hint: "Proceso" },
        { word: "Roberto De Zerbi", hint: "Atrevimiento" },
        { word: "Antonio Conte", hint: "Disciplina" },
        { word: "Massimiliano Allegri", hint: "Pragmatismo" },
        { word: "Luciano Spalletti", hint: "Orden" },
        { word: "Didier Deschamps", hint: "Equilibrio" },
        { word: "Gareth Southgate", hint: "Gestión" },
        { word: "Tite", hint: "Control" },
        { word: "Scaloni", hint: "Unidad" },
        { word: "Fernando Diniz", hint: "Fluidez" },
        { word: "Dorival Júnior", hint: "Adaptación" },
        { word: "Ricardo Gareca", hint: "Confianza" },
        { word: "Gustavo Alfaro", hint: "Motivación" },
        { word: "Jorge Sampaoli", hint: "Caos" },
        { word: "Hernán Crespo", hint: "Transición" },
        { word: "Martín Demichelis", hint: "Orden" },
        { word: "Ramón Díaz", hint: "Autoridad" },
        { word: "Carlos Bianchi", hint: "Eficacia" },
        { word: "Óscar Tabárez", hint: "Proceso" },
        { word: "Manuel Pellegrini", hint: "Serenidad" },
        { word: "Rafael Benítez", hint: "Control" },
        { word: "Vicente del Bosque", hint: "Calma" },
        { word: "Arrigo Sacchi", hint: "Revolución" },
        { word: "Sir Alex Ferguson", hint: "Dominio" },
        { word: "Arsène Wenger", hint: "Visión" },
        { word: "Fabio Capello", hint: "Rigor" },
        { word: "Louis van Gaal", hint: "Dogma" },
        { word: "Johan Cruyff", hint: "Filosofía" },
        { word: "Helenio Herrera", hint: "Carisma" },
        { word: "César Luis Menotti", hint: "Estilo" },
        { word: "Carlos Bilardo", hint: "Resultado" },
        { word: "Ottmar Hitzfeld", hint: "Solidez" },
        { word: "Marcelo Gallardo", hint: "Mentalidad" },
        { word: "Abel Ferreira", hint: "Competitividad" },
        { word: "Jorge Jesus", hint: "Intensidad" },
        { word: "Nuno Espírito Santo", hint: "Orden" }
      ],    
    },
  };

  const defaultPlayers = [
    { id: "1", name: "Jugador 1", color: "#FF3B30" },
    { id: "2", name: "Jugador 2", color: "#34C759" },
    { id: "3", name: "Jugador 3", color: "#007AFF" },
  ];

  // 📦 Cargar jugadores guardados
  useEffect(() => {
    const loadPlayers = async () => {
      try {
        const stored = await AsyncStorage.getItem("players");
        if (stored) {
          setPlayers(JSON.parse(stored));
        } else {
          setPlayers(defaultPlayers);
        }
      } catch (e) {
        console.log("Error cargando jugadores:", e);
        setPlayers(defaultPlayers);
      }
    };
    loadPlayers();
  }, []);

  // 💾 Guardar jugadores cuando cambien
  useEffect(() => {
    if (players.length > 0) {
      AsyncStorage.setItem("players", JSON.stringify(players));
    }
  }, [players]);

  // 🔄 Reiniciar sin borrar jugadores
  const resetGame = () => {
    setImpostorIds([]);
    setWord("");
    setHint("");
    setGameWinner(null);
    setAlivePlayers([]);
  };

  // 🚀 Iniciar partida
  const startGame = (count = impostorCount, category = "general", subCategory = "general") => {
  if (word && hint) {
    return { word, hint, impostorIds, category, subCategory };
  }

  const chosenCategory = defaultWords[category] ? category : "general";
  const chosenSubCategory = defaultWords[chosenCategory][subCategory]
    ? subCategory
    : "general";

  const words = defaultWords[chosenCategory][chosenSubCategory];
  const pick = words[Math.floor(Math.random() * words.length)];

  setWord(pick.word);
  setHint(pick.hint);

  const impostorCountToUse = Math.min(count, players.length - 1);
  const shuffled = [...players].sort(() => Math.random() - 0.5);

  const impostorPlayers = shuffled.slice(0, impostorCountToUse);
  const impostorIds = impostorPlayers.map(p => p.id);

  setImpostorIds(impostorIds); 
console.log("🤖 Impostores generados:", impostorIds);

  return {
  impostorIds,
  word: pick.word,
  hint: pick.hint,
  category: chosenCategory,
  subCategory: chosenSubCategory,
};

};

  return (
    <GameContext.Provider
      value={{
        players,
        setPlayers,
        alivePlayers,
        setAlivePlayers,
        startGame,
        resetGame,
        gameWinner,
        setGameWinner,
        word,
        setWord,
        hint,
        setHint,
        categories: Object.keys(defaultWords),
        getSubCategories: (cat) => Object.keys(defaultWords[cat] || { general: [] }),
        defaultWords,
        category,
        setCategory,
        subCategory,
        setSubCategory,
        soundEnabled,
        setSoundEnabled,
        impostorCount,
        setImpostorCount,
        setHintsEnabled,
        impostorIds,      // ✅ agregar
        setImpostorIds,
        soundEnabled,
        setSoundEnabled, 
      }}
    >
      {children}
    </GameContext.Provider>
  );
}

export const useGameContext = () => useContext(GameContext);